name: CI

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  laravel-tests:
    strategy:
      matrix:
        target: ['8.2', '8.3']

    runs-on: docker-cli
    container: code.itinerare.net/internal/php-node:${{ matrix.target }}-${{ vars.NODE_VER }}-alpine

    steps:
    - name: Set up PHP/Laravel
      uses: https://code.itinerare.net/internal/laravel-setup-action@main
      with:
        php-version: ${{ matrix.target }}
        php-extensions: pdo_sqlite, sqlite3
        composer-auth: ${{ secrets.COMPOSER_AUTH_JSON }}

    - name: Run tests
      run: php artisan test

  pint:
    runs-on: docker-cli
    container: code.itinerare.net/internal/php-node:8.2-${{ vars.NODE_VER }}-alpine
    
    needs: laravel-tests

    steps:
    - name: Set up PHP
      uses: https://code.itinerare.net/internal/php-setup-action@main
      with:
        php-version: 8.2
        composer-auth: ${{ secrets.COMPOSER_AUTH_JSON }}

    - name: Run pint
      run: composer lint

    - name: Commit changes
      uses: https://code.itinerare.net/internal/lint-commit-action@main
      with:
        message: 'refactor: fix PHP styling'
        gpg_key: ${{ secrets.CI_GPG }}
    
    - name: Organize logs
      run: echo "Complete!"

  blade-formatter:
    runs-on: docker
    needs: laravel-tests

    steps:
    - name: Set up node/npm
      uses: https://code.itinerare.net/internal/node-setup-action@main

    - name: Run blade-formatter
      run: npm run format

    - name: Commit changes
      uses: https://code.itinerare.net/internal/lint-commit-action@main
      with:
        message: 'refactor: fix blade formatting'
        gpg_key: ${{ secrets.CI_GPG }}
    
    - name: Organize logs
      run: echo "Complete!"

  rebuild-vite-assets:
    runs-on: docker
    needs: laravel-tests

    steps:
    - name: Set up node/npm
      uses: https://code.itinerare.net/internal/node-setup-action@main

    - name: Run Vite
      run: npm run build

    - name: Commit changes
      uses: https://code.itinerare.net/internal/lint-commit-action@main
      with:
        message: 'chore(deps): rebuild vite assets'
        gpg_key: ${{ secrets.CI_GPG }}
    
    - name: Organize logs
      run: echo "Complete!"
