name: Deploy to prod

on:
  workflow_run:
    workflows: ["Tests"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Deploy to prod
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'ENDSSH'
          cd "${{ vars.DEPLOY_APP_PATH }}"
          git pull
          composer install
          php artisan migrate --force
          php artisan optimize
          php artisan optimize
          ENDSSH
