name: Deploy to prod

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  deploy:
    if: ${{ secrets.SSH_KEY != '' }}
    runs-on: node-alpine

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Deploy to prod
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'ENDSSH'
          cd "${{ vars.DEPLOY_APP_PATH }}"
          php artisan down --render="errors::503" --refresh=30
          git pull
          composer install -no --no-dev
          php artisan migrate --force
          php artisan optimize
          php artisan optimize
          php artisan queue:restart
          php artisan up
          ENDSSH
