name: Deploy to prod

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: docker

    steps:
      - name: Checkout code
        uses: https://code.itinerare.net/internal/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Deploy to prod
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'ENDSSH'
          cd "${{ vars.DEPLOY_APP_PATH }}"
          php artisan down
          git pull
          composer install
          php artisan migrate --force
          php artisan optimize
          php artisan optimize
          php artisan queue:restart
          php artisan up
          ENDSSH
