name: Update changelog

on:
  push:
    tags:
      - '**'

jobs:
  changelog:
    runs-on: docker

    steps:
      - name: Set up PHP
        uses: https://github.com/shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH_JSON }}
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs

      - name: Import GPG key
        uses: https://github.com/crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.CI_GPG }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Generate changelog
        run: composer changelog

      - name: Commit changes
        uses: https://github.com/EndBug/add-and-commit@v9
        with:
          message: 'chore(update): update changelog'
          default_author: github_actions
          author_name: ${{ vars.COMMITTER_NAME }}
          author_email: ${{ vars.COMMITTER_EMAIL }}
