name: Tests

on:
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  laravel-tests:
    strategy:
      matrix:
        target: ['8.2', '8.3']
    uses: itinerare/github-actions/.github/workflows/laravel_tests_sqlite.yml@main
    with:
      php-version: ${{ matrix.target }}
    concurrency:
      group: tests-${{ matrix.target }}-${{ github.ref }}
      cancel-in-progress: true
